# Generated by Django 4.0.5 on 2022-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_image_remove_post_image_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.tag'),
        ),
    ]
