# Generated by Django 4.0.5 on 2022-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_address_address_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='UserProfile'),
        ),
    ]
