# Generated by Django 4.0.5 on 2022-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
