# Generated by Django 4.0.6 on 2022-07-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_post_lat_post_long_alter_post_address_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='long',
        ),
    ]
