# Generated by Django 4.0.6 on 2022-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_remove_post_lat_remove_post_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
